trigger:
  branches:
    include:
      - main
      - features/dev-infra
      

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Format
  displayName: "Terraform Format"
  jobs:
  - job: TerraformFmt
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'sonic-reg'

- stage: Lint
  displayName: "Terraform Lint"
  dependsOn: Format
  jobs:
  - job: TFLint
    steps:
    - task: PowerShell@2
      displayName: Install tflint
      inputs:
        targetType: 'inline'
        script: 'curl -L https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash'

    - task: PowerShell@2
      displayName: Run tflint
      inputs:
        targetType: 'inline'
        script: |
          tflint --init
          tflint
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'

- stage: SecurityScan
  displayName: "Security Scanning"
  dependsOn: Lint
  jobs:
  - job: Tfsec
    displayName: "tfsec Scan"
    continueOnError: true
    steps:
    - task: PowerShell@2
      displayName: Install tfsec
      inputs:
        targetType: 'inline'
        script: 'curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'

    - task: PowerShell@2
      displayName: Run tfsec
      inputs:
        targetType: inline
        script: tfsec .
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'
  
  - job: Checkov
    displayName: "Checkov Scan"
    dependsOn: Tfsec
    continueOnError: true
    steps:
    - task: PowerShell@2
      displayName: Install Checkov
      inputs:
        targetType: 'inline'
        script: pip install checkov
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'

    - task: PowerShell@2
      displayName: Run Checkov
      inputs:
        targetType: inline
        script: checkov -d .
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'


- stage: TerraformPlan
  displayName: "Terraform Plan"
  dependsOn: SecurityScan
  jobs:
  - job: Plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'
        backendServiceArm: 'sonic-reg'
        backendAzureRmResourceGroupName: 'devteam'
        backendAzureRmStorageAccountName: 'devstorage1211'
        backendAzureRmContainerName: 'devcontainer'
        backendAzureRmKey: 'sonic.tfstate'

    
    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'
        environmentServiceNameAzureRM: sonic-reg
        commandOptions: "-out=tfplan"

    - publish: infrastructure_landing_zone/environment/dev
      artifact: terraform-plan
      displayName: "Publish tfplan"

- stage: PreTest
  displayName: "Pre-Apply Policy Tests"
  dependsOn: TerraformPlan
  jobs:
  - job: Conftest
    steps:
    - task: PowerShell@2
      displayName: Install Conftest
      inputs:
        targetType: inline
        script: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64 -O conftest
          chmod +x conftest
          sudo mv conftest /usr/local/bin/conftest
          conftest --version
          workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure_landing_zone/environment/dev'
 
    - task: PowerShell@2
      displayName: Run Conftest
      inputs:
        targetType: inline
        script: |
          conftest test tfplan.json

- stage: CostEstimation
  displayName: "Cost Estimation"
  dependsOn: PreTest
  jobs:
  - job: Infracost
    steps:
    - task: PowerShell@2
      displayName: Install Infracost
      inputs:
        targetType: inline
        script: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

    - task: PowerShell@2
      displayName: Run Infracost
      inputs:
        targetType: inline
        script: |
          infracost breakdown --path=tfplan

- stage: ManualValidation
  displayName: Approval Gates
  pool: server
  dependsOn: CostEstimation
  jobs:
  - job: Manual_Validation
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'ap2101290'


- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: ManualValidation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Apply
    steps:
    - checkout: self
    - download: current
      artifact: terraform-plan
    - script: |
        terraform init
        terraform apply -auto-approve tfplan
      displayName: "Terraform Apply"

- stage: PostTest
  displayName: "Post-Apply Infra Tests"
  dependsOn: Apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Terratest
    steps:
    - task: PowerShell@2
      displayName: Setup Go
      inputs:
        targetType: inline
        script: |
          sudo apt-get update
          sudo apt-get install -y golang-go

    - task: PowerShell@2
      displayName: Run Terratest
      inputs:
        targetType: inline
        script: |
          go test ./terratest/... -v

